on:
  push:
    branches:
      - main
name: 🚀 Deploy to main repo
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # - name: 🔨 Migrations and clearing caches
    #   run: |
    #     php artisan migrate
    #     php artisan optimize
    - name: 🔨 Build Project
      run: |
       
        rm -rf node_modules package-lock.json
        npm install --save axios
        npm i -g vite
        npm i ts-node --save-dev && npm i typescript --save-dev
        npm install -g marked
        npm install --save-dev @types/marked
        npm install marked
        npm run build   
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.nigerialocate.com
        username: agent@agent.gabtaxi.com
        password: EF12@technology
#         local-dir: ./dist/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
