on:
  push:
    branches:
      - staging
name: 🚀 Deploy to staging repo
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # - name: 🔨 Migrations and clearing caches
    #   run: |
    #     php artisan migrate
    #     php artisan optimize

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.nigerialocate.com
        username: "gabAgent@gab-agent.com"
        password: "EF12@technology"
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          
          
          
