on:
  push:
    branches:
      - main
name: 🚀 Deploy to main repo
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # - name: 🔨 Migrations and clearing caches
    #   run: |
    #     php artisan migrate
    #     php artisan optimize
    - name: 🔨 Build Project
      run: |
        npm install
        npm install --save axios
        npm run build   
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.nigerialocate.com
        username: agent@agent.gabtaxi.com
        password: EF12@technology
#         local-dir: ./dist/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
